services:
  app:
    environment:
      DB_HOST: host.docker.internal
      APP_URL: http://localhost:${APP_PORT:-8080}

  queue:
    environment:
      DB_HOST: host.docker.internal
      APP_URL: http://localhost:${APP_PORT:-8080}
